#ifndef HAMMURABI_PARAMS_H_
#define HAMMURABI_PARAMS_H_

#define ROUNDS_COUNT 10
#define MAX_DEAD_PERCENT_BY_HUGER 45

#define START_POPULATION 100
#define START_BUSHELS 2800
#define START_LAND 1000

#define MIN_LAND_PRICE 17
#define MAX_LAND_PRICE 26

#define CITIZEN_CONSUMPTION 20
#define CITIZEN_MAX_CULTIVATED 10
#define MAX_ARRIVED 50

#define BUSHELS_FOR_SEED 0.5
#define MIN_BUSHELS_PER_LAND 1
#define MAX_BUSHELS_PER_LAND 6

#define RATS_MULTIPLIER 0.07
#define PLAGUE_CHANCE 15

#define P_LOW_BORDER 33
#define L_LOW_BORDER 7
#define P_MIDDLE_BORDER 10
#define L_MIDDLE_BORDER 9
#define P_HIGH_BORDER 3
#define L_HIGH_BORDER 10

#endif
